# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12xYdfMyx3cGp3u06Ilwh9w3NjbgWYtOn
"""

def hitung_nilai_tpa(nilai_verbal, nilai_numerikal, nilai_figural):
    # Hitung rata-rata nilai dan bagi dengan 100%
    rata_rata = (nilai_verbal + nilai_numerikal + nilai_figural) / 3
    nilai_tpa = ((rata_rata / 100)*600)+200

    return nilai_tpa

# Masukkan nilai-nilai verbal, numerikal, dan figural
nilai_verbal = float(input("Masukkan Nilai Verbal: "))
nilai_numerikal = float(input("Masukkan Nilai Numerikal: "))
nilai_figural = float(input("Masukkan Nilai Figural: "))

# Hitung nilai TPA
nilai_tpa = hitung_nilai_tpa(nilai_verbal, nilai_numerikal, nilai_figural)

# Tampilkan nilai TPA
print("Nilai TPA:", nilai_tpa)